// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// compute_r2_cpp
arma::mat compute_r2_cpp(const arma::mat& X, int digits, int n_threads);
RcppExport SEXP _LDxBlocks_compute_r2_cpp(SEXP XSEXP, SEXP digitsSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type digits(digitsSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_r2_cpp(X, digits, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// compute_rV2_cpp
arma::mat compute_rV2_cpp(const arma::mat& X, int digits, int n_threads);
RcppExport SEXP _LDxBlocks_compute_rV2_cpp(SEXP XSEXP, SEXP digitsSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type digits(digitsSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_rV2_cpp(X, digits, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// maf_filter_cpp
LogicalVector maf_filter_cpp(const arma::mat& G, double maf_cut);
RcppExport SEXP _LDxBlocks_maf_filter_cpp(SEXP GSEXP, SEXP maf_cutSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type G(GSEXP);
    Rcpp::traits::input_parameter< double >::type maf_cut(maf_cutSEXP);
    rcpp_result_gen = Rcpp::wrap(maf_filter_cpp(G, maf_cut));
    return rcpp_result_gen;
END_RCPP
}
// build_adj_matrix_cpp
arma::imat build_adj_matrix_cpp(const arma::mat& LD, double threshold);
RcppExport SEXP _LDxBlocks_build_adj_matrix_cpp(SEXP LDSEXP, SEXP thresholdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type LD(LDSEXP);
    Rcpp::traits::input_parameter< double >::type threshold(thresholdSEXP);
    rcpp_result_gen = Rcpp::wrap(build_adj_matrix_cpp(LD, threshold));
    return rcpp_result_gen;
END_RCPP
}
// col_r2_cpp
arma::vec col_r2_cpp(const arma::mat& X, int query_col);
RcppExport SEXP _LDxBlocks_col_r2_cpp(SEXP XSEXP, SEXP query_colSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type query_col(query_colSEXP);
    rcpp_result_gen = Rcpp::wrap(col_r2_cpp(X, query_col));
    return rcpp_result_gen;
END_RCPP
}
// compute_r2_sparse_cpp
List compute_r2_sparse_cpp(const arma::mat& X, const arma::ivec& bp, int max_bp_dist, double threshold, int n_threads);
RcppExport SEXP _LDxBlocks_compute_r2_sparse_cpp(SEXP XSEXP, SEXP bpSEXP, SEXP max_bp_distSEXP, SEXP thresholdSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type bp(bpSEXP);
    Rcpp::traits::input_parameter< int >::type max_bp_dist(max_bp_distSEXP);
    Rcpp::traits::input_parameter< double >::type threshold(thresholdSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_r2_sparse_cpp(X, bp, max_bp_dist, threshold, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// boundary_scan_cpp
IntegerVector boundary_scan_cpp(const arma::mat& X, int start, int end, int half_w, double threshold);
RcppExport SEXP _LDxBlocks_boundary_scan_cpp(SEXP XSEXP, SEXP startSEXP, SEXP endSEXP, SEXP half_wSEXP, SEXP thresholdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type start(startSEXP);
    Rcpp::traits::input_parameter< int >::type end(endSEXP);
    Rcpp::traits::input_parameter< int >::type half_w(half_wSEXP);
    Rcpp::traits::input_parameter< double >::type threshold(thresholdSEXP);
    rcpp_result_gen = Rcpp::wrap(boundary_scan_cpp(X, start, end, half_w, threshold));
    return rcpp_result_gen;
END_RCPP
}
// build_hap_strings_cpp
Rcpp::CharacterVector build_hap_strings_cpp(Rcpp::IntegerMatrix geno_block, std::string na_char);
RcppExport SEXP _LDxBlocks_build_hap_strings_cpp(SEXP geno_blockSEXP, SEXP na_charSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix >::type geno_block(geno_blockSEXP);
    Rcpp::traits::input_parameter< std::string >::type na_char(na_charSEXP);
    rcpp_result_gen = Rcpp::wrap(build_hap_strings_cpp(geno_block, na_char));
    return rcpp_result_gen;
END_RCPP
}
// resolve_overlap_cpp
arma::imat resolve_overlap_cpp(arma::imat blocks, const arma::mat& adj_mat, int k_rep);
RcppExport SEXP _LDxBlocks_resolve_overlap_cpp(SEXP blocksSEXP, SEXP adj_matSEXP, SEXP k_repSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::imat >::type blocks(blocksSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type adj_mat(adj_matSEXP);
    Rcpp::traits::input_parameter< int >::type k_rep(k_repSEXP);
    rcpp_result_gen = Rcpp::wrap(resolve_overlap_cpp(blocks, adj_mat, k_rep));
    return rcpp_result_gen;
END_RCPP
}
// block_snp_ranges_cpp
Rcpp::List block_snp_ranges_cpp(const Rcpp::IntegerVector& snp_pos, const Rcpp::IntegerVector& block_sb, const Rcpp::IntegerVector& block_eb);
RcppExport SEXP _LDxBlocks_block_snp_ranges_cpp(SEXP snp_posSEXP, SEXP block_sbSEXP, SEXP block_ebSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type snp_pos(snp_posSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type block_sb(block_sbSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type block_eb(block_ebSEXP);
    rcpp_result_gen = Rcpp::wrap(block_snp_ranges_cpp(snp_pos, block_sb, block_eb));
    return rcpp_result_gen;
END_RCPP
}
// extract_chr_haplotypes_cpp
Rcpp::List extract_chr_haplotypes_cpp(const Rcpp::IntegerMatrix& geno_chr, const Rcpp::IntegerVector& snp_pos, const Rcpp::IntegerVector& block_sb, const Rcpp::IntegerVector& block_eb, int min_snps, double min_freq, int top_n, std::string na_char);
RcppExport SEXP _LDxBlocks_extract_chr_haplotypes_cpp(SEXP geno_chrSEXP, SEXP snp_posSEXP, SEXP block_sbSEXP, SEXP block_ebSEXP, SEXP min_snpsSEXP, SEXP min_freqSEXP, SEXP top_nSEXP, SEXP na_charSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::IntegerMatrix& >::type geno_chr(geno_chrSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type snp_pos(snp_posSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type block_sb(block_sbSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type block_eb(block_ebSEXP);
    Rcpp::traits::input_parameter< int >::type min_snps(min_snpsSEXP);
    Rcpp::traits::input_parameter< double >::type min_freq(min_freqSEXP);
    Rcpp::traits::input_parameter< int >::type top_n(top_nSEXP);
    Rcpp::traits::input_parameter< std::string >::type na_char(na_charSEXP);
    rcpp_result_gen = Rcpp::wrap(extract_chr_haplotypes_cpp(geno_chr, snp_pos, block_sb, block_eb, min_snps, min_freq, top_n, na_char));
    return rcpp_result_gen;
END_RCPP
}
// extract_chr_haplotypes_phased_cpp
Rcpp::List extract_chr_haplotypes_phased_cpp(const Rcpp::IntegerMatrix& hap1_chr, const Rcpp::IntegerMatrix& hap2_chr, const Rcpp::IntegerVector& snp_pos, const Rcpp::IntegerVector& block_sb, const Rcpp::IntegerVector& block_eb, int min_snps, double min_freq, int top_n, std::string na_char);
RcppExport SEXP _LDxBlocks_extract_chr_haplotypes_phased_cpp(SEXP hap1_chrSEXP, SEXP hap2_chrSEXP, SEXP snp_posSEXP, SEXP block_sbSEXP, SEXP block_ebSEXP, SEXP min_snpsSEXP, SEXP min_freqSEXP, SEXP top_nSEXP, SEXP na_charSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::IntegerMatrix& >::type hap1_chr(hap1_chrSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerMatrix& >::type hap2_chr(hap2_chrSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type snp_pos(snp_posSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type block_sb(block_sbSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type block_eb(block_ebSEXP);
    Rcpp::traits::input_parameter< int >::type min_snps(min_snpsSEXP);
    Rcpp::traits::input_parameter< double >::type min_freq(min_freqSEXP);
    Rcpp::traits::input_parameter< int >::type top_n(top_nSEXP);
    Rcpp::traits::input_parameter< std::string >::type na_char(na_charSEXP);
    rcpp_result_gen = Rcpp::wrap(extract_chr_haplotypes_phased_cpp(hap1_chr, hap2_chr, snp_pos, block_sb, block_eb, min_snps, min_freq, top_n, na_char));
    return rcpp_result_gen;
END_RCPP
}
// impute_and_filter_cpp
Rcpp::List impute_and_filter_cpp(Rcpp::IntegerMatrix geno, double min_callrate, int method);
RcppExport SEXP _LDxBlocks_impute_and_filter_cpp(SEXP genoSEXP, SEXP min_callrateSEXP, SEXP methodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix >::type geno(genoSEXP);
    Rcpp::traits::input_parameter< double >::type min_callrate(min_callrateSEXP);
    Rcpp::traits::input_parameter< int >::type method(methodSEXP);
    rcpp_result_gen = Rcpp::wrap(impute_and_filter_cpp(geno, min_callrate, method));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_LDxBlocks_compute_r2_cpp", (DL_FUNC) &_LDxBlocks_compute_r2_cpp, 3},
    {"_LDxBlocks_compute_rV2_cpp", (DL_FUNC) &_LDxBlocks_compute_rV2_cpp, 3},
    {"_LDxBlocks_maf_filter_cpp", (DL_FUNC) &_LDxBlocks_maf_filter_cpp, 2},
    {"_LDxBlocks_build_adj_matrix_cpp", (DL_FUNC) &_LDxBlocks_build_adj_matrix_cpp, 2},
    {"_LDxBlocks_col_r2_cpp", (DL_FUNC) &_LDxBlocks_col_r2_cpp, 2},
    {"_LDxBlocks_compute_r2_sparse_cpp", (DL_FUNC) &_LDxBlocks_compute_r2_sparse_cpp, 5},
    {"_LDxBlocks_boundary_scan_cpp", (DL_FUNC) &_LDxBlocks_boundary_scan_cpp, 5},
    {"_LDxBlocks_build_hap_strings_cpp", (DL_FUNC) &_LDxBlocks_build_hap_strings_cpp, 2},
    {"_LDxBlocks_resolve_overlap_cpp", (DL_FUNC) &_LDxBlocks_resolve_overlap_cpp, 3},
    {"_LDxBlocks_block_snp_ranges_cpp", (DL_FUNC) &_LDxBlocks_block_snp_ranges_cpp, 3},
    {"_LDxBlocks_extract_chr_haplotypes_cpp", (DL_FUNC) &_LDxBlocks_extract_chr_haplotypes_cpp, 8},
    {"_LDxBlocks_extract_chr_haplotypes_phased_cpp", (DL_FUNC) &_LDxBlocks_extract_chr_haplotypes_phased_cpp, 9},
    {"_LDxBlocks_impute_and_filter_cpp", (DL_FUNC) &_LDxBlocks_impute_and_filter_cpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_LDxBlocks(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
