// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// compute_r2_cpp
arma::mat compute_r2_cpp(const arma::mat& X, int digits, int n_threads);
RcppExport SEXP _LDxBlocks_compute_r2_cpp(SEXP XSEXP, SEXP digitsSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type digits(digitsSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_r2_cpp(X, digits, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// compute_rV2_cpp
arma::mat compute_rV2_cpp(const arma::mat& X, int digits, int n_threads);
RcppExport SEXP _LDxBlocks_compute_rV2_cpp(SEXP XSEXP, SEXP digitsSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type digits(digitsSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_rV2_cpp(X, digits, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// maf_filter_cpp
LogicalVector maf_filter_cpp(const arma::mat& G, double maf_cut);
RcppExport SEXP _LDxBlocks_maf_filter_cpp(SEXP GSEXP, SEXP maf_cutSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type G(GSEXP);
    Rcpp::traits::input_parameter< double >::type maf_cut(maf_cutSEXP);
    rcpp_result_gen = Rcpp::wrap(maf_filter_cpp(G, maf_cut));
    return rcpp_result_gen;
END_RCPP
}
// build_adj_matrix_cpp
arma::imat build_adj_matrix_cpp(const arma::mat& LD, double threshold);
RcppExport SEXP _LDxBlocks_build_adj_matrix_cpp(SEXP LDSEXP, SEXP thresholdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type LD(LDSEXP);
    Rcpp::traits::input_parameter< double >::type threshold(thresholdSEXP);
    rcpp_result_gen = Rcpp::wrap(build_adj_matrix_cpp(LD, threshold));
    return rcpp_result_gen;
END_RCPP
}
// col_r2_cpp
arma::vec col_r2_cpp(const arma::mat& X, int query_col);
RcppExport SEXP _LDxBlocks_col_r2_cpp(SEXP XSEXP, SEXP query_colSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type query_col(query_colSEXP);
    rcpp_result_gen = Rcpp::wrap(col_r2_cpp(X, query_col));
    return rcpp_result_gen;
END_RCPP
}
// compute_r2_sparse_cpp
List compute_r2_sparse_cpp(const arma::mat& X, const arma::ivec& bp, int max_bp_dist, double threshold);
RcppExport SEXP _LDxBlocks_compute_r2_sparse_cpp(SEXP XSEXP, SEXP bpSEXP, SEXP max_bp_distSEXP, SEXP thresholdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type bp(bpSEXP);
    Rcpp::traits::input_parameter< int >::type max_bp_dist(max_bp_distSEXP);
    Rcpp::traits::input_parameter< double >::type threshold(thresholdSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_r2_sparse_cpp(X, bp, max_bp_dist, threshold));
    return rcpp_result_gen;
END_RCPP
}
// boundary_scan_cpp
IntegerVector boundary_scan_cpp(const arma::mat& X, int start, int end, int half_w, double threshold);
RcppExport SEXP _LDxBlocks_boundary_scan_cpp(SEXP XSEXP, SEXP startSEXP, SEXP endSEXP, SEXP half_wSEXP, SEXP thresholdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type start(startSEXP);
    Rcpp::traits::input_parameter< int >::type end(endSEXP);
    Rcpp::traits::input_parameter< int >::type half_w(half_wSEXP);
    Rcpp::traits::input_parameter< double >::type threshold(thresholdSEXP);
    rcpp_result_gen = Rcpp::wrap(boundary_scan_cpp(X, start, end, half_w, threshold));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_LDxBlocks_compute_r2_cpp", (DL_FUNC) &_LDxBlocks_compute_r2_cpp, 3},
    {"_LDxBlocks_compute_rV2_cpp", (DL_FUNC) &_LDxBlocks_compute_rV2_cpp, 3},
    {"_LDxBlocks_maf_filter_cpp", (DL_FUNC) &_LDxBlocks_maf_filter_cpp, 2},
    {"_LDxBlocks_build_adj_matrix_cpp", (DL_FUNC) &_LDxBlocks_build_adj_matrix_cpp, 2},
    {"_LDxBlocks_col_r2_cpp", (DL_FUNC) &_LDxBlocks_col_r2_cpp, 2},
    {"_LDxBlocks_compute_r2_sparse_cpp", (DL_FUNC) &_LDxBlocks_compute_r2_sparse_cpp, 4},
    {"_LDxBlocks_boundary_scan_cpp", (DL_FUNC) &_LDxBlocks_boundary_scan_cpp, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_LDxBlocks(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
