# ─────────────────────────────────────────────────────────────────────────────
# R/example_data.R  –  Roxygen documentation for LDxBlocks example datasets
# ─────────────────────────────────────────────────────────────────────────────
#
# All four datasets are generated by data-raw/generate_example_data.R and
# shipped as compressed .rda files in data/.
#
# Flat-file copies for read_geno() demonstrations live in inst/extdata/:
#   example_genotypes_numeric.csv   (numeric dosage)
#   example_genotypes.hmp.txt       (HapMap)
#   example_genotypes.vcf           (VCF v4.2)
# ─────────────────────────────────────────────────────────────────────────────


#' Example Genotype Matrix
#'
#' @description
#' A simulated additive genotype matrix for 120 individuals and 200 SNPs
#' spanning three chromosomes, designed to exhibit clear LD block structure
#' suitable for demonstrating \code{\link{Big_LD}} and
#' \code{\link{run_Big_LD_all_chr}}.
#'
#' @section Structure:
#' The 200 SNPs are divided across three chromosomes (70, 70, 60 SNPs
#' respectively). Each chromosome contains three distinct LD blocks separated
#' by short stretches (5 SNPs) of low-LD singletons and a 50 kb inter-block
#' gap:
#'
#' \describe{
#'   \item{Chromosome 1}{Three blocks of 25, 20, and 25 SNPs.}
#'   \item{Chromosome 2}{Three blocks of 30, 20, and 20 SNPs.}
#'   \item{Chromosome 3}{Three blocks of 20, 20, and 20 SNPs.}
#' }
#'
#' Within each block, SNPs were generated by copying a common founder haplotype
#' and applying random single-allele flips (flip rate 4\%) to each SNP
#' independently, producing strong within-block LD (r² > 0.7 for most pairs).
#' Between-block SNPs were simulated independently from binomial distributions
#' with randomised allele frequencies to produce near-zero LD.
#'
#' @format A numeric matrix with 120 rows (individuals, named \code{ind001}
#'   to \code{ind120}) and 200 columns (SNPs, named \code{rs1001} to
#'   \code{rs3070}). Values are additive dosages in \{0, 1, 2\} with no
#'   missing data.
#'
#' @source Simulated with \code{data-raw/generate_example_data.R}.
#'   Seed: \code{set.seed(20250407)}.
#'
#' @seealso \code{\link{ldx_snp_info}}, \code{\link{ldx_blocks}},
#'   \code{\link{ldx_gwas}}, \code{\link{run_Big_LD_all_chr}}
#'
#' @examples
#' data(ldx_geno)
#' dim(ldx_geno)           # 120 200
#' range(ldx_geno)         # 0 2
#'
#' # Compute r² for the first 30 SNPs
#' r2 <- compute_r2(ldx_geno[, 1:30])
#' image(r2, main = "r² — first 30 SNPs (chr1 block 1)")
"ldx_geno"


#' Example SNP Information Table
#'
#' @description
#' Genomic metadata for the 200 SNPs in \code{\link{ldx_geno}}.
#'
#' @format A \code{data.frame} with 200 rows and 5 columns:
#' \describe{
#'   \item{\code{SNP}}{Character. SNP identifier (e.g. \code{"rs1001"}).}
#'   \item{\code{CHR}}{Character. Chromosome label (\code{"1"}, \code{"2"},
#'     or \code{"3"}). No \code{chr} prefix — consistent with the normalisation
#'     applied by \code{\link{read_geno}}.}
#'   \item{\code{POS}}{Integer. Base-pair position on the chromosome. Positions
#'     increase monotonically within each chromosome; inter-block gaps of
#'     approximately 50,000 bp separate LD blocks.}
#'   \item{\code{REF}}{Character. Reference allele (A/C/G/T).}
#'   \item{\code{ALT}}{Character. Alternate allele.}
#' }
#'
#' @source Simulated with \code{data-raw/generate_example_data.R}.
#'
#' @seealso \code{\link{ldx_geno}}, \code{\link{ldx_blocks}}
#'
#' @examples
#' data(ldx_snp_info)
#' head(ldx_snp_info)
#' table(ldx_snp_info$CHR)   # 70 70 60
"ldx_snp_info"


#' Example LD Block Table
#'
#' @description
#' A reference LD block table for \code{\link{ldx_geno}}, matching the nine
#' blocks (three per chromosome) embedded in the simulation. This object is
#' used in examples and tests as the expected output of
#' \code{\link{run_Big_LD_all_chr}} on \code{ldx_geno}.
#'
#' @format A \code{data.frame} with 9 rows and 8 columns:
#' \describe{
#'   \item{\code{start}}{Integer. Index of the first SNP in the block
#'     (1-based, over the full 200-SNP set).}
#'   \item{\code{end}}{Integer. Index of the last SNP.}
#'   \item{\code{start.rsID}}{Character. SNP ID at the block start.}
#'   \item{\code{end.rsID}}{Character. SNP ID at the block end.}
#'   \item{\code{start.bp}}{Integer. Base-pair position of the block start.}
#'   \item{\code{end.bp}}{Integer. Base-pair position of the block end.}
#'   \item{\code{CHR}}{Character. Chromosome label.}
#'   \item{\code{length_bp}}{Integer. \code{end.bp - start.bp + 1}.}
#' }
#'
#' @source Derived analytically from the simulation structure in
#'   \code{data-raw/generate_example_data.R}; matches expected
#'   \code{run_Big_LD_all_chr(ldx_geno, ldx_snp_info, CLQcut = 0.6)} output.
#'
#' @seealso \code{\link{ldx_geno}}, \code{\link{run_Big_LD_all_chr}},
#'   \code{\link{summarise_blocks}}
#'
#' @examples
#' data(ldx_blocks)
#' ldx_blocks
#' summarise_blocks(ldx_blocks)
"ldx_blocks"


#' Example GWAS Marker Table
#'
#' @description
#' Twenty toy GWAS-significant markers drawn from the simulated LD blocks,
#' used to demonstrate \code{\link{tune_LD_params}} parameter auto-tuning.
#' All 20 markers fall within one of the nine simulated blocks in
#' \code{\link{ldx_blocks}}, so a correctly parameterised run of
#' \code{tune_LD_params} should return zero unassigned markers.
#'
#' @format A \code{data.frame} with 20 rows and 5 columns:
#' \describe{
#'   \item{\code{Marker}}{Character. SNP identifier, matching entries in
#'     \code{ldx_snp_info$SNP}.}
#'   \item{\code{CHR}}{Character. Chromosome label.}
#'   \item{\code{POS}}{Integer. Base-pair position.}
#'   \item{\code{P}}{Numeric. Toy p-value in (1e-8, 0.001).}
#'   \item{\code{trait}}{Character. Toy trait label (\code{"TraitA"} or
#'     \code{"TraitB"}), assigned randomly at 60/40 probability. Used to
#'     demonstrate multi-trait pleiotropic block detection in
#'     \code{\link{define_qtl_regions}}. When a single trait is analysed,
#'     this column is simply ignored or the \code{trait_col} argument omitted.}
#' }
#'
#' @source Simulated with \code{data-raw/generate_example_data.R}.
#'   Seed: \code{set.seed(42)}.
#'
#' @seealso \code{\link{tune_LD_params}}, \code{\link{define_qtl_regions}},
#'   \code{\link{ldx_geno}}, \code{\link{ldx_snp_info}}
#'
#' @examples
#' data(ldx_gwas)
#' head(ldx_gwas)
#' # All markers should fall within ldx_blocks:
#' data(ldx_blocks)
#' data(ldx_snp_info)
#' all(ldx_gwas$Marker %in% ldx_snp_info$SNP)
"ldx_gwas"
