# -----------------------------------------------------------------------------
# R/example_data.R  -  Roxygen documentation for LDxBlocks example datasets
# -----------------------------------------------------------------------------
#
# All six datasets are generated by data-raw/generate_example_data.R and
# shipped as compressed .rda files in data/.
#
# Flat-file copies for read_geno() demonstrations live in inst/extdata/:
#   example_genotypes_numeric.csv   (numeric dosage)
#   example_genotypes.hmp.txt       (HapMap)
#   example_genotypes.vcf           (VCF v4.2)
#   example_blues.csv               (pre-adjusted BLUEs: id, YLD, RES)
# -----------------------------------------------------------------------------


#' Example Genotype Matrix
#'
#' @description
#' A simulated additive genotype matrix for 120 individuals and 230 SNPs
#' spanning three chromosomes, designed to exhibit clear LD block structure
#' suitable for demonstrating \code{\link{run_Big_LD_all_chr}}
#' and \code{\link{extract_haplotypes}}.
#'
#' @section Structure:
#' The 230 SNPs are divided across three chromosomes (80, 80, 70 SNPs
#' respectively). Each chromosome contains three distinct LD blocks separated
#' by short stretches (5 SNPs) of low-LD singletons and a 50 kb inter-block
#' gap:
#'
#' \describe{
#'   \item{Chromosome 1}{Three blocks of 25, 20, and 25 SNPs.}
#'   \item{Chromosome 2}{Three blocks of 30, 20, and 20 SNPs.}
#'   \item{Chromosome 3}{Three blocks of 20, 20, and 20 SNPs.}
#' }
#'
#' Within each block, SNPs were generated using a founder-haplotype model:
#' K = 4 binary founder haplotypes are drawn per block, then each individual
#' is assigned a diploid combination of two founders (flip rate 1\%, MAF
#' enforced >= 10\% per SNP). This guarantees at most K(K+1)/2 = 10
#' distinct diplotype classes per block (~12 individuals per class), ensuring
#' sufficient diversity for \code{\link{estimate_diplotype_effects}}.
#' Between-block SNPs are simulated independently from binomial distributions
#' with randomised allele frequencies to produce near-zero LD.
#'
#' @format A numeric matrix with 120 rows (individuals, named \code{ind001}
#'   to \code{ind120}) and 230 columns (SNPs). SNP identifiers follow the
#'   pattern \code{rs{CHR}{count}}: chromosome 1 uses \code{rs1001}--\code{rs1080},
#'   chromosome 2 uses \code{rs2001}--\code{rs2080}, chromosome 3 uses
#'   \code{rs3001}--\code{rs3070}. Values are additive dosages in
#'   \{0, 1, 2\} with no missing data.
#'
#' @source Simulated with \code{data-raw/generate_example_data.R}
#'   using a founder-haplotype model (K = 4 founders per block).
#'   Seed: \code{set.seed(20250407)}.
#'
#' @seealso \code{\link{ldx_snp_info}}, \code{\link{ldx_blocks}},
#'   \code{\link{ldx_gwas}}, \code{\link{run_Big_LD_all_chr}}
#'
#' @examples
#' data(ldx_geno)
#' dim(ldx_geno)           # 120 230
#' range(ldx_geno)         # 0 2
#'
#' # Compute r^2 for the first 30 SNPs
#' r2 <- compute_r2(ldx_geno[, 1:30])
#' image(r2, main = "r^2 - first 30 SNPs (chr1 block 1)")
#'
#' \donttest{
#' # Sliding-window diversity scan (independent of LD blocks)
#' data(ldx_snp_info)
#' scan <- scan_diversity_windows(
#'   geno_matrix  = ldx_geno,
#'   snp_info     = ldx_snp_info,
#'   window_bp    = 50000L,
#'   step_bp      = 25000L,
#'   min_snps_win = 3L
#' )
#' head(scan[, c("CHR","win_mid","n_snps","He","freq_dominant")])
#' }
"ldx_geno"


#' Example SNP Information Table
#'
#' @description
#' Genomic metadata for the 230 SNPs in \code{\link{ldx_geno}}.
#'
#' @format A \code{data.frame} with 230 rows and 5 columns:
#' \describe{
#'   \item{\code{SNP}}{Character. SNP identifier (e.g. \code{"rs1001"}).}
#'   \item{\code{CHR}}{Character. Chromosome label (\code{"1"}, \code{"2"},
#'     or \code{"3"}). No \code{chr} prefix - consistent with the normalisation
#'     applied by \code{\link{read_geno}}.}
#'   \item{\code{POS}}{Integer. Base-pair position on the chromosome. Positions
#'     increase monotonically within each chromosome; inter-block gaps of
#'     approximately 50,000 bp separate LD blocks.}
#'   \item{\code{REF}}{Character. Reference allele (A/C/G/T).}
#'   \item{\code{ALT}}{Character. Alternate allele.}
#' }
#'
#' @source Simulated with \code{data-raw/generate_example_data.R}.
#'
#' @seealso \code{\link{ldx_geno}}, \code{\link{ldx_blocks}}
#'
#' @examples
#' data(ldx_snp_info)
#' head(ldx_snp_info)
#' table(ldx_snp_info$CHR)   # 80 80 70
#'
#' \donttest{
#' # Compute LD decay and chromosome-specific decay distances
#' data(ldx_geno)
#' decay <- compute_ld_decay(
#'   geno         = ldx_geno,
#'   snp_info     = ldx_snp_info,
#'   sampling     = "random",
#'   r2_threshold = "both",
#'   n_pairs      = 3000L,
#'   verbose      = FALSE
#' )
#' decay$critical_r2_param   # background LD level
#' decay$decay_dist          # per-chromosome decay distances (kb)
#' }
"ldx_snp_info"


#' Example LD Block Table
#'
#' @description
#' A reference LD block table for \code{\link{ldx_geno}}, matching the nine
#' blocks (three per chromosome) embedded in the simulation. This object is
#' used in examples and tests as the expected output of
#' \code{\link{run_Big_LD_all_chr}} on \code{ldx_geno}.
#'
#' @format A \code{data.frame} with 9 rows and 8 columns:
#' \describe{
#'   \item{\code{start}}{Integer. Index of the first SNP in the block
#'     (1-based, over the full 230-SNP set).}
#'   \item{\code{end}}{Integer. Index of the last SNP.}
#'   \item{\code{start.rsID}}{Character. SNP ID at the block start.}
#'   \item{\code{end.rsID}}{Character. SNP ID at the block end.}
#'   \item{\code{start.bp}}{Integer. Base-pair position of the block start.}
#'   \item{\code{end.bp}}{Integer. Base-pair position of the block end.}
#'   \item{\code{CHR}}{Character. Chromosome label.}
#'   \item{\code{length_bp}}{Integer. \code{end.bp - start.bp + 1}.}
#' }
#'
#' @source Derived analytically from the founder-haplotype simulation in
#'   \code{data-raw/generate_example_data.R}; matches expected
#'   \code{run_Big_LD_all_chr(ldx_geno, ldx_snp_info, CLQcut = 0.6)} output.
#'
#' @seealso \code{\link{ldx_geno}}, \code{\link{run_Big_LD_all_chr}},
#'   \code{\link{summarise_blocks}}
#'
#' @examples
#' data(ldx_blocks)
#' ldx_blocks
#' summarise_blocks(ldx_blocks)
#'
#' \donttest{
#' # Compare haplotype allele frequencies between two sample groups
#' data(ldx_geno, ldx_snp_info)
#' haps <- extract_haplotypes(ldx_geno, ldx_snp_info, ldx_blocks)
#' ids  <- rownames(ldx_geno)
#' cmp  <- compare_haplotype_populations(
#'   haplotypes  = haps,
#'   group1      = ids[1:60],
#'   group2      = ids[61:120],
#'   group1_name = "cycle1",
#'   group2_name = "cycle2"
#' )
#' head(cmp[, c("block_id","n1","n2","FST","divergent")])
#' }
"ldx_blocks"


#' Example GWAS Marker Table
#'
#' @description
#' Twenty toy GWAS markers drawn from simulated LD blocks for use with
#' \code{\link{tune_LD_params}} and \code{\link{define_qtl_regions}}.
#' All 20 markers fall within LD blocks, but not all nine blocks are
#' represented: chromosome 3 contributes markers only from its first block;
#' blocks 2 and 3 of chromosome 3 have no GWAS markers.
#' A correctly parameterised run of \code{tune_LD_params} should return
#' zero unassigned markers.
#'
#' @format A \code{data.frame} with 20 rows and 5 columns:
#' \describe{
#'   \item{\code{Marker}}{Character. SNP identifier, matching entries in
#'     \code{ldx_snp_info$SNP}.}
#'   \item{\code{CHR}}{Character. Chromosome label.}
#'   \item{\code{POS}}{Integer. Base-pair position.}
#'   \item{\code{P}}{Numeric. Toy p-value. Eight markers have P < 1e-6
#'     (clearly significant), seven have P in (1e-5, 1e-3) (suggestive),
#'     and five have P in (1e-3, 0.05) (sub-threshold).}
#'   \item{\code{trait}}{Character. Toy trait label (\code{"TraitA"} or
#'     \code{"TraitB"}), assigned randomly at 60/40 probability. Used to
#'     demonstrate multi-trait pleiotropic block detection in
#'     \code{\link{define_qtl_regions}}. When a single trait is analysed,
#'     this column is simply ignored or the \code{trait_col} argument omitted.}
#' }
#'
#' @source Simulated with \code{data-raw/generate_example_data.R}.
#'   Seed: \code{set.seed(42)}.
#'
#' @seealso \code{\link{tune_LD_params}}, \code{\link{define_qtl_regions}},
#'   \code{\link{ldx_geno}}, \code{\link{ldx_snp_info}}
#'
#' @examples
#' data(ldx_gwas)
#' head(ldx_gwas)
#' # All markers should fall within ldx_blocks:
#' data(ldx_blocks)
#' data(ldx_snp_info)
#' all(ldx_gwas$Marker %in% ldx_snp_info$SNP)
"ldx_gwas"


#' Pre-Adjusted Phenotype Means (BLUEs) for Genomic Prediction Examples
#'
#' @description
#' Simulated pre-adjusted phenotype means (BLUEs) for 120 individuals across
#' two traits, designed for use with \code{\link{run_haplotype_prediction}}.
#' In a real analysis these would come from fitting a mixed model (ASReml-R,
#' lme4, or SpATS) to field trial data. Here they are generated as
#' polygenic trait values from random SNP effects plus noise, then
#' standardised to zero mean and unit variance.
#'
#' A flat-file copy is also available at
#' \code{system.file("extdata", "example_blues.csv", package = "LDxBlocks")}.
#'
#' @format A \code{data.frame} with 120 rows and 3 columns:
#' \describe{
#'   \item{\code{id}}{Character. Individual identifier (\code{ind001} to
#'     \code{ind120}), matching \code{rownames(ldx_geno)}.}
#'   \item{\code{YLD}}{Numeric. Simulated yield-like BLUE (standardised).}
#'   \item{\code{RES}}{Numeric. Simulated resistance-like BLUE (standardised).}
#' }
#'
#' @source Generated by \code{data-raw/generate_example_data.R}.
#'   Seed: \code{set.seed(20250408)}.
#'
#' @seealso \code{\link{run_haplotype_prediction}},
#'   \code{\link{ldx_geno}}, \code{\link{ldx_blocks}}
#'
#' @examples
#' blues_file <- system.file("extdata", "example_blues.csv",
#'                           package = "LDxBlocks")
#' blues <- read.csv(blues_file)
#' head(blues)
#'
#' \dontrun{
#' # Single-trait prediction (YLD)
#' data(ldx_geno, ldx_snp_info, ldx_blocks)
#' res <- run_haplotype_prediction(
#'   geno_matrix = ldx_geno,
#'   snp_info    = ldx_snp_info,
#'   blocks      = ldx_blocks,
#'   blues       = blues,
#'   id_col      = "id",
#'   blue_col    = "YLD"
#' )
#' res$block_importance[res$block_importance$important, ]
#'
#' # Multi-trait prediction (YLD + RES simultaneously)
#' res_mt <- run_haplotype_prediction(
#'   geno_matrix     = ldx_geno,
#'   snp_info        = ldx_snp_info,
#'   blocks          = ldx_blocks,
#'   blues           = blues,
#'   id_col          = "id",
#'   blue_cols       = c("YLD", "RES"),
#'   importance_rule = "any"
#' )
#' res_mt$solver_used   # 'sommer' or 'rrBLUP'
#' res_mt$block_importance[res_mt$block_importance$important_any,
#'   c("block_id", "var_scaled_YLD", "var_scaled_RES", "n_traits_important")]
#' }
#'
#' \donttest{
#' # Cross-validate genomic prediction accuracy
#' data(ldx_geno, ldx_snp_info, ldx_blocks)
#' blues_file <- system.file("extdata", "example_blues.csv",
#'                           package = "LDxBlocks")
#' blues <- read.csv(blues_file)
#' cv <- cv_haplotype_prediction(
#'   geno_matrix = ldx_geno,
#'   snp_info    = ldx_snp_info,
#'   blocks      = ldx_blocks,
#'   blues       = blues,
#'   k           = 3L,
#'   id_col      = "id",
#'   blue_col    = "YLD",
#'   verbose     = FALSE
#' )
#' cv$pa_mean
#' }
"ldx_blues"


#' Per-Environment BLUEs for Stability Analysis Examples
#'
#' @description
#' Simulated pre-adjusted phenotype means (BLUEs) for 120 individuals across
#' two environments, formatted as a named list for use with
#' \code{\link{run_haplotype_stability}} and \code{\link{cv_haplotype_prediction}}.
#' Each element is a named numeric vector (names = individual IDs, values = BLUEs)
#' representing adjusted means from one environment or growing season.
#'
#' In a real analysis these would come from fitting environment-specific mixed
#' models. Here they are generated from the same polygenic trait values as
#' \code{\link{ldx_blues}} with environment-specific offsets and noise.
#'
#' @format A named \code{list} with 2 elements:
#' \describe{
#'   \item{\code{env1}}{Named numeric vector of length 120. BLUEs for
#'     environment 1 (base yield values with small noise).}
#'   \item{\code{env2}}{Named numeric vector of length 120. BLUEs for
#'     environment 2 (mean shift of 0.4 units above env1, simulating a
#'     more favourable environment).}
#' }
#' Names of each vector match \code{rownames(ldx_geno)} (\code{ind001}
#' to \code{ind120}).
#'
#' @source Generated by \code{data-raw/generate_example_data.R}.
#'   Seed: \code{set.seed(20250409)}.
#'
#' @seealso \code{\link{run_haplotype_stability}},
#'   \code{\link{cv_haplotype_prediction}},
#'   \code{\link{ldx_blues}}, \code{\link{ldx_geno}}
#'
#' @examples
#' data(ldx_blues_list)
#' names(ldx_blues_list)          # "env1" "env2"
#' length(ldx_blues_list$env1)    # 120
#' head(ldx_blues_list$env1)
#'
#' # Mean BLUE difference between environments (expected ~0.4)
#' mean(ldx_blues_list$env2 - ldx_blues_list$env1)
#'
#' \donttest{
#' # Finlay-Wilkinson stability analysis across two environments
#' data(ldx_geno, ldx_snp_info, ldx_blocks)
#' stab <- run_haplotype_stability(
#'   geno_matrix = ldx_geno,
#'   snp_info    = ldx_snp_info,
#'   blocks      = ldx_blocks,
#'   blues_list  = ldx_blues_list,
#'   verbose     = FALSE
#' )
#' # Stable blocks (regression slope b not significantly different from 1)
#' head(stab[stab$stable, c("block_id","b","b_se","r2_fw")])
#' }
"ldx_blues_list"
