# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compute_r2_cpp <- function(X, digits = -1L, n_threads = 1L) {
    .Call(`_LDxBlocks_compute_r2_cpp`, X, digits, n_threads)
}

compute_rV2_cpp <- function(X, digits = -1L, n_threads = 1L) {
    .Call(`_LDxBlocks_compute_rV2_cpp`, X, digits, n_threads)
}

maf_filter_cpp <- function(G, maf_cut = 0.05) {
    .Call(`_LDxBlocks_maf_filter_cpp`, G, maf_cut)
}

build_adj_matrix_cpp <- function(LD, threshold) {
    .Call(`_LDxBlocks_build_adj_matrix_cpp`, LD, threshold)
}

col_r2_cpp <- function(X, query_col) {
    .Call(`_LDxBlocks_col_r2_cpp`, X, query_col)
}

compute_r2_sparse_cpp <- function(X, bp, max_bp_dist, threshold = 0.0, n_threads = 1L) {
    .Call(`_LDxBlocks_compute_r2_sparse_cpp`, X, bp, max_bp_dist, threshold, n_threads)
}

boundary_scan_cpp <- function(X, start, end, half_w, threshold) {
    .Call(`_LDxBlocks_boundary_scan_cpp`, X, start, end, half_w, threshold)
}

build_hap_strings_cpp <- function(geno_block, na_char = ".") {
    .Call(`_LDxBlocks_build_hap_strings_cpp`, geno_block, na_char)
}

